<a href="https://colab.research.google.com/github/srinu211/CreditCardFraudDetection.ipynb/blob/main/CreditCardFraudDetection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

CREDIT CARD FRAUD TRANSACTION DETECTION MODEL
TECHNOHACKS EDUTECH OFFICIAL INTERNSHIP PROGRAM: (Batch:33, March 2024)


Problem Statement: Use a dataset of credit card transactions and build a model that can identify potentially fraudulent transactions

IMPORTING LIBARIES:

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.25.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [ ]:
import pandas as pd

In [ ]:
file_path = '/content/creditcard.csv'
credit_card_data = pd.read_csv(file_path)

In [ ]:
!pip install tidyverse

Collecting tidyverse
  Downloading tidyverse-0.1.0-py3-none-any.whl (1.1 kB)
Collecting plotnine<0.11.0,>=0.10.1 (from tidyverse)
  Downloading plotnine-0.10.1-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 6.1 MB/s eta 0:00:00
Collecting siuba<0.4.0,>=0.3.0 (from tidyverse)
  Downloading siuba-0.3.0-py3-none-any.whl (142 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.1/142.1 kB 13.6 MB/s eta 0:00:00
Requirement already satisfied: matplotlib>=3.5.0 in /usr/local/lib/python3.10/dist-packages (from plotnine<0.11.0,>=0.10.1->tidyverse) (3.7.1)
Requirement already satisfied: mizani>=0.8.1 in /usr/local/lib/python3.10/dist-packages (from plotnine<0.11.0,>=0.10.1->tidyverse) (0.9.3)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.10/dist-packages (from plotnine<0.11.0,>=0.10.1->tidyverse) (1.25.2)
Requirement already satisfied: pandas>=1.3.5 in /usr/local/lib/python3.10/dist-packages (from plotnine<0.11.0,>=0.10.1->tidyverse) (2.0.3)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.10/dist-packages (from plotnine<0.11.0,>=0.10.1->tidyverse) (0.5.6)
Requirement already satisfied: scipy>=1.5.0 in /usr/local/lib/python3.10/dist-packages (from plotnine<0.11.0,>=0.10.1->tidyverse) (1.11.4)
Requirement already satisfied: statsmodels>=0.13.2 in /usr/local/lib/python3.10/dist-packages (from plotnine<0.11.0,>=0.10.1->tidyverse) (0.14.1)
Requirement already satisfied: SQLAlchemy>=1.2.19 in /usr/local/lib/python3.10/dist-packages (from siuba<0.4.0,>=0.3.0->tidyverse) (2.0.29)
Requirement already satisfied: PyYAML>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from siuba<0.4.0,>=0.3.0->tidyverse) (6.0.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.5.0->plotnine<0.11.0,>=0.10.1->tidyverse) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.5.0->plotnine<0.11.0,>=0.10.1->tidyverse) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.5.0->plotnine<0.11.0,>=0.10.1->tidyverse) (4.50.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.5.0->plotnine<0.11.0,>=0.10.1->tidyverse) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.5.0->plotnine<0.11.0,>=0.10.1->tidyverse) (24.0)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.5.0->plotnine<0.11.0,>=0.10.1->tidyverse) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.5.0->plotnine<0.11.0,>=0.10.1->tidyverse) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.5.0->plotnine<0.11.0,>=0.10.1->tidyverse) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.3.5->plotnine<0.11.0,>=0.10.1->tidyverse) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.3.5->plotnine<0.11.0,>=0.10.1->tidyverse) (2024.1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.1->plotnine<0.11.0,>=0.10.1->tidyverse) (1.16.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from SQLAlchemy>=1.2.19->siuba<0.4.0,>=0.3.0->tidyverse) (4.10.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from SQLAlchemy>=1.2.19->siuba<0.4.0,>=0.3.0->tidyverse) (3.0.3)
Installing collected packages: siuba, plotnine, tidyverse
  Attempting uninstall: plotnine
    Found existing installation: plotnine 0.12.4
    Uninstalling plotnine-0.12.4:
      Successfully uninstalled plotnine-0.12.4
Successfully installed plotnine-0.10.1 siuba-0.3.0 tidyverse-0.1.0

In [ ]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
13949,24754,1.252924,-0.182189,-0.802716,-0.210981,1.916713,3.643624,-0.778711,0.818295,1.706962,...,-0.497088,-1.211285,0.043809,0.964159,0.442030,0.261483,-0.051402,0.005112,23.74,0.0
13950,24756,-0.346979,-2.103284,-0.685061,1.961605,-0.401125,0.473632,1.133816,-0.256528,0.893409,...,0.359662,-0.316275,-0.864259,-0.279881,0.491802,-0.353996,-0.149931,0.129795,794.20,0.0
13951,24759,-6.053652,-5.988723,0.810413,-0.011811,1.308135,-0.590803,-0.725838,-0.234840,1.624646,...,-0.771970,1.474668,3.176363,-0.302410,0.052529,-0.373871,-0.700463,2.508443,60.00,0.0
13952,24759,1.169121,-1.284945,0.032717,-0.681670,0.660598,4.412578,-1.913115,1.076592,1.501230,...,-0.557596,-0.882435,-0.041523,0.975445,0.297229,0.550515,0.015029,0.032067,90.00,0.0
13953,24759,-6.917152,5.854171,-1.652458,-1.488884,-0.833891,-0.344418,0.393789,0.379968,6.133597,...,-1.404681,-1.124694,0.174333,-0.528234,0.990685,-0.035875,1.071374,-0.168831,NaN,NaN

In [ ]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13954 entries, 0 to 13953
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    13954 non-null  int64
 1   V1      13954 non-null  float64
 2   V2      13954 non-null  float64
 3   V3      13954 non-null  float64
 4   V4      13954 non-null  float64
 5   V5      13954 non-null  float64
 6   V6      13954 non-null  float64
 7   V7      13954 non-null  float64
 8   V8      13954 non-null  float64
 9   V9      13954 non-null  float64
 10  V10     13954 non-null  float64
 11  V11     13954 non-null  float64
 12  V12     13954 non-null  float64
 13  V13     13954 non-null  float64
 14  V14     13954 non-null  float64
 15  V15     13954 non-null  float64
 16  V16     13954 non-null  float64
 17  V17     13954 non-null  float64
 18  V18     13954 non-null  float64
 19  V19     13954 non-null  float64
 20  V20     13954 non-null  float64
 21  V21     13954 non-null  float64
 22  V22     13954 non-null  float64
 23  V23     13954 non-null  float64
 24  V24     13954 non-null  float64
 25  V25     13954 non-null  float64
 26  V26     13954 non-null  float64
 27  V27     13954 non-null  float64
 28  V28     13954 non-null  float64
 29  Amount  13953 non-null  float64
 30  Class   13953 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 3.3 MB

In [ ]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    1
Class     1
dtype: int64

We are having null values replace it my mean using fillna

In [ ]:
credit_card_data.fillna(credit_card_data.mean(), inplace=True)

In [ ]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

BINARY CLASSIFICATION

After making these adjustments, you should have a 'Class' column with only binary values (0 or 1), where 0 represents non-fraudulent transactions, and 1 represents fraudulent transactions.

In [ ]:
credit_card_data['Class'] = credit_card_data['Class'].astype(int)
credit_card_data = credit_card_data[(credit_card_data['Class'] == 0) | (credit_card_data['Class'] == 1)]

In [ ]:
credit_card_data['Class'].value_counts()

Class
0    13898
1       56
Name: count, dtype: int64

HIGHLY UNBALANCED DATA

In [ ]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [ ]:

print(legit.shape)
print(fraud.shape)

(13898, 31)
(56, 31)

In [ ]:
# statistical measures of the data
legit.Amount.describe()

count    13898.000000
mean        63.773917
std        177.158128
min          0.000000
25%          5.770000
50%         15.900000
75%         52.385000
max       7712.430000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count      56.000000
mean       90.815893
std       310.308450
min         0.000000
25%         1.000000
50%         1.000000
75%         1.025000
max      1809.680000
Name: Amount, dtype: float64

In [ ]:
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,10112.535185,-0.217575,0.266654,0.887044,0.276662,-0.107562,0.13671,-0.131424,-0.020357,1.005829,...,0.021006,-0.068782,-0.158300,-0.034819,0.013026,0.117991,0.034344,0.009642,0.002317,63.773917
1,12262.107143,-4.727948,4.660436,-9.328536,6.783464,-2.890388,-2.03036,-6.578337,1.028374,-2.981468,...,0.453283,0.116896,0.048132,-0.225526,-0.452514,-0.124184,0.333325,0.793484,-0.046177,90.815893

TRY TO BALANCE DATASET:

*Isolation Forest is a powerful tool for anomaly (Outliers) detection *

In [ ]:
import pandas as pd
from sklearn.ensemble import IsolationForest

# Separate the features (X) and target (y)
X = credit_card_data.drop('Class', axis=1)
y = credit_card_data['Class']

# Instantiate the Isolation Forest model
isolation_forest = IsolationForest(contamination='auto', random_state=42)

# Fit the model to the data
isolation_forest.fit(X)

# Predict outliers (fraudulent transactions)
y_pred = isolation_forest.predict(X)

# Convert predictions to binary labels (1 for inliers, -1 for outliers)
y_pred_labels = [1 if p == 1 else 0 for p in y_pred]

# Combine the predicted labels with the original data for further analysis
credit_card_data['Anomaly'] = y_pred_labels

In [ ]:

# Separate the data into legitimate (non-fraudulent) and potential fraudulent transactions
legit_transactions = credit_card_data[credit_card_data['Anomaly'] == 1]
potential_fraud_transactions = credit_card_data[credit_card_data['Anomaly'] == 0]

print("Shape of legit_transactions:", legit_transactions.shape)
print("Shape of potential_fraud_transactions:", potential_fraud_transactions.shape)

DATA AUGMENTATION:

In [ ]:
import pandas as pd
import numpy as np
from imblearn.under_sampling import RandomUnderSampler
# Separate the features (X) and target (y) for both legit and potential fraud transactions
X_legit = legit_transactions.drop('Class', axis=1)
y_legit = legit_transactions['Class']

X_fraud = potential_fraud_transactions.drop('Class', axis=1)
y_fraud = potential_fraud_transactions['Class']
desired_fraud_samples = 300
additional_fraud_samples_needed = desired_fraud_samples - len(X_fraud)

# Create additional samples through data augmentation (example: random perturbations)
augmented_fraud_samples = []
for _ in range(additional_fraud_samples_needed):
    random_idx = np.random.randint(0, len(X_fraud))
    new_sample = X_fraud.iloc[random_idx].copy()
    new_sample += np.random.normal(0, 0.01, len(new_sample))
    augmented_fraud_samples.append(new_sample)

# Convert the augmented samples list to a DataFrame
augmented_fraud_transactions = pd.DataFrame(augmented_fraud_samples, columns=X_fraud.columns)

In [ ]:
print(augmented_fraud_transactions.shape)

(0, 31)

In [ ]:
legit_sample = legit.sample(n=217)
augmented_fraud_transactions['Class'] = 1

In [ ]:
balanced_dataset = pd.concat([legit_sample, augmented_fraud_transactions], ignore_index=True)

In [ ]:
print(legit_sample.head())

        Time        V1        V2        V3        V4        V5        V6  \
127       80 -0.655264  0.409899  1.289156 -0.325043  0.545669 -0.349811
7471   10162  1.182880  0.051146  0.841107  0.018382 -0.500300 -0.286042
10627  17833  0.993725  1.054307 -1.577749  1.537197  1.697540  0.564523
4064    3724  1.039952 -0.152470  1.390009  1.471145 -0.969043  0.157308
7163    9387 -5.489814  1.561072  0.726760 -0.476520 -0.024480 -0.703520

             V7        V8        V9  ...       V21       V22       V23  \
127    0.648240  0.036063  0.078701  ... -0.155727 -0.477390 -0.126525
7471  -0.415972 -0.024078  1.273732  ... -0.180742 -0.224945  0.138876
10627  0.210922  0.319476  0.675820  ... -0.190118 -0.153934 -0.084938
4064  -0.765444  0.196767  2.047291  ... -0.148737 -0.138825 -0.028047
7163   0.879357 -0.877083  5.499426  ... -1.350095 -0.041123  0.677093

            V24       V25       V26       V27       V28  Amount  Class
127   -0.443628 -0.012118  0.143173  0.049783  0.118280   32.51      0
7471   0.236495 -0.007872  0.862932 -0.079217 -0.006461    4.00      0
10627 -1.424830  0.458697 -0.220467  0.073157  0.066380   14.99      0
4064   0.243695  0.317788 -0.465594  0.029132  0.026213   46.80      0
7163   0.377902  0.886612  0.287220  0.450214  0.050597    0.01      0

[5 rows x 31 columns]

In [ ]:
print(augmented_fraud_transactions.head())

Empty DataFrame
Columns: [Time, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13, V14, V15, V16, V17, V18, V19, V20, V21, V22, V23, V24, V25, V26, V27, V28, Amount, Anomaly, Class]
Index: []

[0 rows x 32 columns]

In [ ]:
balanced_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V22,V23,V24,V25,V26,V27,V28,Amount,Class,Anomaly
0,80,-0.655264,0.409899,1.289156,-0.325043,0.545669,-0.349811,0.648240,0.036063,0.078701,...,-0.477390,-0.126525,-0.443628,-0.012118,0.143173,0.049783,0.118280,32.51,0,NaN
1,10162,1.182880,0.051146,0.841107,0.018382,-0.500300,-0.286042,-0.415972,-0.024078,1.273732,...,-0.224945,0.138876,0.236495,-0.007872,0.862932,-0.079217,-0.006461,4.00,0,NaN
2,17833,0.993725,1.054307,-1.577749,1.537197,1.697540,0.564523,0.210922,0.319476,0.675820,...,-0.153934,-0.084938,-1.424830,0.458697,-0.220467,0.073157,0.066380,14.99,0,NaN
3,3724,1.039952,-0.152470,1.390009,1.471145,-0.969043,0.157308,-0.765444,0.196767,2.047291,...,-0.138825,-0.028047,0.243695,0.317788,-0.465594,0.029132,0.026213,46.80,0,NaN
4,9387,-5.489814,1.561072,0.726760,-0.476520,-0.024480,-0.703520,0.879357,-0.877083,5.499426,...,-0.041123,0.677093,0.377902,0.886612,0.287220,0.450214,0.050597,0.01,0,NaN

In [ ]:

balanced_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V22,V23,V24,V25,V26,V27,V28,Amount,Class,Anomaly
212,1549,-0.975437,0.700053,2.180777,-0.276133,0.522233,-0.521061,1.135711,-0.070862,0.079413,...,-0.127844,-0.351791,0.342088,0.690008,-0.598515,-0.151632,-0.174043,9.99,0,NaN
213,24251,-0.470300,0.747507,0.344485,-0.631696,0.021346,-0.719841,0.289545,0.332516,0.939953,...,0.003708,0.008592,0.002827,-0.493140,0.787645,-0.164107,-0.022364,24.99,0,NaN
214,571,-2.990622,2.962638,-0.980844,0.071904,-1.795238,-1.335733,-1.143681,2.134599,-0.377240,...,-0.890628,0.278109,0.301391,0.137764,0.103233,0.052097,0.001938,9.99,0,NaN
215,871,-1.366797,-0.381816,2.909364,0.452824,0.646125,0.074504,-0.043701,-0.323218,0.698467,...,0.120994,-0.434589,0.063623,0.059021,0.365410,-0.447739,-0.363027,15.30,0,NaN
216,5372,-0.868767,1.301044,1.293434,0.067153,-0.062524,0.140671,-0.771663,-2.523458,0.515227,...,-0.432289,0.200169,-0.143132,-0.380599,0.008105,-0.049524,0.068505,1.98,0,NaN

BALANCED THE DATASET APRROXIMATELY:

In [ ]:
balanced_dataset['Class'].value_counts()

Class
0    217
Name: count, dtype: int64

In [ ]:

balanced_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Anomaly
Class,,,,,,,,,,,,,,,,,,,,,
0,9945.147465,-0.03741,0.200696,0.822559,0.357744,-0.084371,0.059594,-0.147839,-0.052073,0.98659,...,-0.10514,-0.251538,-0.056504,-0.046974,0.111864,0.027342,0.028318,0.010048,65.547419,NaN

In [ ]:

X = balanced_dataset.drop(columns='Class', axis=1)
Y = balanced_dataset['Class']

In [ ]:

print(X)

      Time        V1        V2        V3        V4        V5        V6  \
0       80 -0.655264  0.409899  1.289156 -0.325043  0.545669 -0.349811
1    10162  1.182880  0.051146  0.841107  0.018382 -0.500300 -0.286042
2    17833  0.993725  1.054307 -1.577749  1.537197  1.697540  0.564523
3     3724  1.039952 -0.152470  1.390009  1.471145 -0.969043  0.157308
4     9387 -5.489814  1.561072  0.726760 -0.476520 -0.024480 -0.703520
..     ...       ...       ...       ...       ...       ...       ...
212   1549 -0.975437  0.700053  2.180777 -0.276133  0.522233 -0.521061
213  24251 -0.470300  0.747507  0.344485 -0.631696  0.021346 -0.719841
214    571 -2.990622  2.962638 -0.980844  0.071904 -1.795238 -1.335733
215    871 -1.366797 -0.381816  2.909364  0.452824  0.646125  0.074504
216   5372 -0.868767  1.301044  1.293434  0.067153 -0.062524  0.140671

           V7        V8        V9  ...       V21       V22       V23  \
0    0.648240  0.036063  0.078701  ... -0.155727 -0.477390 -0.126525
1   -0.415972 -0.024078  1.273732  ... -0.180742 -0.224945  0.138876
2    0.210922  0.319476  0.675820  ... -0.190118 -0.153934 -0.084938
3   -0.765444  0.196767  2.047291  ... -0.148737 -0.138825 -0.028047
4    0.879357 -0.877083  5.499426  ... -1.350095 -0.041123  0.677093
..        ...       ...       ...  ...       ...       ...       ...
212  1.135711 -0.070862  0.079413  ... -0.096646 -0.127844 -0.351791
213  0.289545  0.332516  0.939953  ... -0.026034  0.003708  0.008592
214 -1.143681  2.134599 -0.377240  ... -0.184759 -0.890628  0.278109
215 -0.043701 -0.323218  0.698467  ... -0.219791  0.120994 -0.434589
216 -0.771663 -2.523458  0.515227  ... -1.575998 -0.432289  0.200169

          V24       V25       V26       V27       V28  Amount  Anomaly
0   -0.443628 -0.012118  0.143173  0.049783  0.118280   32.51      NaN
1    0.236495 -0.007872  0.862932 -0.079217 -0.006461    4.00      NaN
2   -1.424830  0.458697 -0.220467  0.073157  0.066380   14.99      NaN
3    0.243695  0.317788 -0.465594  0.029132  0.026213   46.80      NaN
4    0.377902  0.886612  0.287220  0.450214  0.050597    0.01      NaN
..        ...       ...       ...       ...       ...     ...      ...
212  0.342088  0.690008 -0.598515 -0.151632 -0.174043    9.99      NaN
213  0.002827 -0.493140  0.787645 -0.164107 -0.022364   24.99      NaN
214  0.301391  0.137764  0.103233  0.052097  0.001938    9.99      NaN
215  0.063623  0.059021  0.365410 -0.447739 -0.363027   15.30      NaN
216 -0.143132 -0.380599  0.008105 -0.049524  0.068505    1.98      NaN

[217 rows x 31 columns]

In [ ]:

print(Y)

0      0
1      0
2      0
3      0
4      0
      ..
212    0
213    0
214    0
215    0
216    0
Name: Class, Length: 217, dtype: int64

DEALING WITH NaN VALUES:

In [ ]:
from sklearn.impute import SimpleImputer
# Instantiate the SimpleImputer with a strategy to fill missing values with the mean
imputer = SimpleImputer(strategy='mean')
X_imputed = imputer.fit_transform(X)

In [ ]:

X_train, X_test, Y_train, Y_test = train_test_split(X_imputed, Y, test_size=0.2, stratify=Y, random_state=2)

LOGISTIC REGRESSION :

data contains NaN values in the Anomaly column of X,Logistic regression does not accept missing values encoded as NaN natively, and it's important to handle missing values before training the model so ... Imputation: If dropping rows is not suitable, you can impute the missing values using various techniques.

In [ ]:
model = LogisticRegression()

In [ ]:
print(Y_train.value_counts())

Class
0    173
Name: count, dtype: int64

In [ ]:
if len(Y_train.value_counts()) == 1:
    print("The target variable has only one class.")

The target variable has only one class.

In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook.
On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.

Random Forest

Random Forest is generally more robust to overfitting compared to a single decision tree or linear models like logistic regression.

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Assuming you have X_train_scaled, X_test_scaled, Y_train, and Y_test as your training and testing data

# Instantiate the Random Forest Classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the classifier on the training data
rf_classifier.fit(X_train_scaled, Y_train)

# Make predictions on the test data
Y_pred = rf_classifier.predict(X_test_scaled)

# Evaluate the model's performance
accuracy = accuracy_score(Y_test, Y_pred)
print("Accuracy:", accuracy)

# Get other evaluation metrics like classification report and confusion matrix
print(classification_report(Y_test, Y_pred))
print(confusion_matrix(Y_test, Y_pred))

Accuracy: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        44

    accuracy                           1.00        44
   macro avg       1.00      1.00      1.00        44
weighted avg       1.00      1.00      1.00        44

[[44]]

ACCURACY INCREASED TO 95%